#!/usr/bin/python

"""
This sample ParticipantHandler can be installed into skynet:

make_skynet_participant -n example -p /usr/share/doc/python-boss-skynet/example-participant

"""
from SkyNET import (WorkItemCtrl, ParticipantCtrl, Workitem)

class ParticipantHandler(object):
    def handle_wi_control(self, ctrl):
        pass
    
    def handle_lifecycle_control(self, ctrl):
        pass
    
    def handle_wi(self, wi):
        if 'debug_dump' in wi.fields():
            print json.dumps(wi.to_h(), sort_keys=True, indent=4)
        fields = wi.fields()
        print "successful"
        wi.set_result(True)
