#!/usr/bin/python

"""
This sample ParticipantHandler can be installed into skynet:

skynet make_participant -n notify -p /usr/share/doc/python-boss-skynet/example-notify-participant

This participant 'reports' on the contents field (no matter where they
come from).

"""

# The message containers are a minimal requirement
from SkyNET import (WorkItemCtrl, ParticipantCtrl, Workitem)

# Additional python can be used but bear in mind that this code is run
# in the context of an AMQP message handling system

class ParticipantHandler(object):
    def handle_wi_control(self, ctrl):
        pass
    
    def handle_lifecycle_control(self, ctrl):
        pass
    
    def handle_wi(self, wi):

        # We may want to examine the fields structure
        if 'debug_dump' in wi.fields():
            print json.dumps(wi.to_h(), sort_keys=True, indent=4)

        # Some meaningless logic
        if "contents" in wi.fields():
            print "Send email saying : %s" % wi.fields()["contents"]
            wi.set_result(True)
        else:
            print "Nothing to say"
            wi.set_result(False)
