#!/usr/bin/python

"""
This sample ParticipantHandler can be installed into skynet:

skynet make_participant -n notify -p /usr/share/doc/python-boss-skynet/example-notify-participant

This participant 'reports' on the contents field (no matter where they
come from).

"""

# The message containers are a minimal requirement
from SkyNET import (WorkItemCtrl, ParticipantCtrl, Workitem)

# Additional python can be used but bear in mind that this code is run
# in the context of an AMQP message handling system

class ParticipantHandler(object):
    def handle_wi_control(self, ctrl):
        pass
    
    def handle_lifecycle_control(self, ctrl):
        pass
    
    def handle_wi(self, wi):

        # We may want to examine the fields structure
        if wi.fields.debug_dump:
            print wi.dump()

        # Some meaningless logic
        if wi.fields.contents:
            print "Send email saying : %s" % wi.contents
            wi.result = True
        else:
            print "Nothing to say"
            wi.result = False
