#!/usr/bin/python

# The message containers are a minimal requirement
from SkyNET import (WorkItemCtrl, ParticipantCtrl, Workitem)

class ParticipantHandler(object):
    def handle_wi_control(self, ctrl):
        pass
    
    def handle_lifecycle_control(self, ctrl):
        pass
    
    def handle_wi(self, wi):
        pass

