#!/usr/bin/env python
import sys
import os
from SkyNET import Exo
from setproctitle import setproctitle


def update_env(envfile):
    if os.path.exists(envfile):
        with open(envfile, 'r') as conf:
            lines = [line.strip() if not line.strip().startswith('#')
                     else "" for line in conf.readlines()]
            for line in lines:
                if line:
                    key, value = line.split("=", 1)
                    os.environ.update({key.strip(): value.strip()})


# check for 1 arg
if not len(sys.argv) == 2:
    print "SkyNET Exo needs one argument, full path to a config file"
    sys.exit(1)

update_env("/etc/skynet/skynet.env")
exo = Exo(sys.argv[1])
update_env("/etc/skynet/%s.env" % exo.name)

if "SUPERVISOR_PROCESS_NAME" in os.environ:
    setproctitle("participant %s" % os.environ["SUPERVISOR_PROCESS_NAME"])
else:
    setproctitle("participant %s" % exo.name)

exo.run()
